<a href="https://colab.research.google.com/github/bruno-ba/python-lab/blob/main/exercicios_youtube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estudo e aplicações de exemplos demonstrados práticos do canal [Socrática](https://www.youtube.com/channel/UCW6TXMZ5Pq6yL6_k5NZ2e0Q)

## [Iterators, Iterables, and Itertools in Python || Python Tutorial || Learn Python Programming ](https://www.youtube.com/watch?v=WR7mO_jYN9g)

Iterable
Sequence =  Interable + Ordered

common sequences: lists, tuples, strings, bytes

In [ ]:
list = ['CX32', 'GSOF', 'Emily', 'Franz', 'Rex']
for element in list:
  print(element)

CX32
GSOF
Emily
Franz
Rex


In [ ]:
for letter in 'Socratica':
  print(letter)

S
o
c
r
a
t
i
c
a


In [ ]:
for byte in b'Binary':
  print(byte)

66
105
110
97
114
121


In [ ]:
#for digit in 299792458:
 # print(digit)

In [ ]:
c = 299792458
digits = [int(x) for x in str(c)]
for digit in digits:
  print(digit)

2
9
9
7
9
2
4
5
8


In [ ]:
usernames =('Rainer', 'Alfons', 'Flatsheep')
looper1 = usernames.__iter__()
type(looper1)

tuple_iterator

In [ ]:
looper1.__next__()

'Rainer'

In [ ]:
looper1.__next__()

'Alfons'

In [ ]:
looper1.__next__()

'Flatsheep'

In [ ]:
looper1.__next__()

StopIteration: ignored

In [ ]:
usernames

('Rainer', 'Alfons', 'Flatsheep')

In [ ]:
looper2 = iter(usernames)

In [ ]:
next(looper2)

'Rainer'

In [ ]:
next(looper2)

'Alfons'

In [ ]:
next(looper2)

'Flatsheep'

In [ ]:
next(looper2)

StopIteration: ignored

In [ ]:
users = ['laust', 'leoMoon', 'JennaSys', 'dgletts']

In [ ]:
for user in users:
  print(user)

laust
leoMoon
JennaSys
dgletts


In [ ]:
looper = iter(users)
while True:
  try:
    user = next(looper)
    print(user)
  except StopIteration:
    break

laust
leoMoon
JennaSys
dgletts


In [ ]:
class Portifolio:
  def __init__(self):
    #key=ticker, Value = number of shares
    self.holdings = {} 
  
  def buy(self, ticker, shares):
    self.holdings[ticker] = self.holdings.get(ticker, 0) + shares
  
  def sell(self, ticker, shares):
    self.holdings[ticker] = self.holdings.get(ticker, 0) - shares
  
  def __iter__(self):
    return iter(self.holdings.items())

In [ ]:
 p = Portifolio()
 p.buy('ALPHA', 15)
 p.buy('BETA', 23)
 p.buy('GAMMA', 9)
 p.buy('GAMMA', 20)

 for (ticker, shares) in p:
   print(ticker, shares)


ALPHA 15
BETA 23
GAMMA 29


In [ ]:
import itertools

In [ ]:
dir(itertools)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_grouper',
 '_tee',
 '_tee_dataobject',
 'accumulate',
 'chain',
 'combinations',
 'combinations_with_replacement',
 'compress',
 'count',
 'cycle',
 'dropwhile',
 'filterfalse',
 'groupby',
 'islice',
 'permutations',
 'product',
 'repeat',
 'starmap',
 'takewhile',
 'tee',
 'zip_longest']

In [ ]:
help(itertools.chain)

Help on class chain in module itertools:

class chain(builtins.object)
 |  chain(*iterables) --> chain object
 |  
 |  Return a chain object whose .__next__() method returns elements from the
 |  first iterable until it is exhausted, then elements from the next
 |  iterable, until all of the iterables are exhausted.
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  __setstate__(...)
 |      Set state information for unpickling.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  from_iterable(...) from builtins.type
 |      chain.from_iterable(iterable) --> chain object
 |      
 |      Alternate chain() constructor taking a single iterable argument
 |      that evaluat

In [ ]:
d = iter('MADAGASCAR')

In [ ]:
type(d)

str_iterator

In [ ]:
while True:
  try:
    print(next(d))
  except StopIteration:
    break

M
A
D
A
G
A
S
C
A
R


In [ ]:
import itertools
ranks = list(range(2,11))+['J', 'Q', 'K', 'A']
            

In [ ]:
ranks

[2, 3, 4, 5, 6, 7, 8, 9, 10, 'J', 'Q', 'K', 'A']

In [ ]:
ranks = [str(rank) for rank in ranks]
print(ranks)

['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']


In [ ]:
suits = ['Hearts', 'Clubs', 'Diamonds', 'Spades']

In [ ]:
deck = [card for card in itertools.product(ranks, suits)]
print(f'decks: {len(deck)}')
print(deck)

decks: 52
[('2', 'Hearts'), ('2', 'Clubs'), ('2', 'Diamonds'), ('2', 'Spades'), ('3', 'Hearts'), ('3', 'Clubs'), ('3', 'Diamonds'), ('3', 'Spades'), ('4', 'Hearts'), ('4', 'Clubs'), ('4', 'Diamonds'), ('4', 'Spades'), ('5', 'Hearts'), ('5', 'Clubs'), ('5', 'Diamonds'), ('5', 'Spades'), ('6', 'Hearts'), ('6', 'Clubs'), ('6', 'Diamonds'), ('6', 'Spades'), ('7', 'Hearts'), ('7', 'Clubs'), ('7', 'Diamonds'), ('7', 'Spades'), ('8', 'Hearts'), ('8', 'Clubs'), ('8', 'Diamonds'), ('8', 'Spades'), ('9', 'Hearts'), ('9', 'Clubs'), ('9', 'Diamonds'), ('9', 'Spades'), ('10', 'Hearts'), ('10', 'Clubs'), ('10', 'Diamonds'), ('10', 'Spades'), ('J', 'Hearts'), ('J', 'Clubs'), ('J', 'Diamonds'), ('J', 'Spades'), ('Q', 'Hearts'), ('Q', 'Clubs'), ('Q', 'Diamonds'), ('Q', 'Spades'), ('K', 'Hearts'), ('K', 'Clubs'), ('K', 'Diamonds'), ('K', 'Spades'), ('A', 'Hearts'), ('A', 'Clubs'), ('A', 'Diamonds'), ('A', 'Spades')]


In [ ]:
for card in deck:
  index, value = card
  print(index, value)

2 Hearts
2 Clubs
2 Diamonds
2 Spades
3 Hearts
3 Clubs
3 Diamonds
3 Spades
4 Hearts
4 Clubs
4 Diamonds
4 Spades
5 Hearts
5 Clubs
5 Diamonds
5 Spades
6 Hearts
6 Clubs
6 Diamonds
6 Spades
7 Hearts
7 Clubs
7 Diamonds
7 Spades
8 Hearts
8 Clubs
8 Diamonds
8 Spades
9 Hearts
9 Clubs
9 Diamonds
9 Spades
10 Hearts
10 Clubs
10 Diamonds
10 Spades
J Hearts
J Clubs
J Diamonds
J Spades
Q Hearts
Q Clubs
Q Diamonds
Q Spades
K Hearts
K Clubs
K Diamonds
K Spades
A Hearts
A Clubs
A Diamonds
A Spades


In [ ]:
hands = [hand for hand in itertools.combinations(deck, 5)]

In [ ]:
print(len(hands)) 

2598960


## [Generators in Python || Python Tutorial || Learn Python Programming](https://www.youtube.com/watch?v=gMompY5MyPg)

In [ ]:
def f():
  return 1
  return 2
  return 3

In [ ]:
print(f())

1


In [ ]:
def g():
  yield 1
  yield 2
  yield 3

In [ ]:
print(g())

<generator object g at 0x7ff93ad97c50>


In [ ]:
for x in g():
  print(x)

1
2
3


In [ ]:
import string

In [ ]:
def letters():
  for c in string.ascii_lowercase:
    yield c

In [ ]:
for letter in letters():
  print(letter)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


In [ ]:
import itertools
def prime_numbers():
  #Handle the first prime
  yield 2
  prime_cache = [2]
  # loop over positive, odd integers
  for n in itertools.count(3,2):
    is_prime = True#check to see if any prime number divides n 
    for p in prime_cache:
      if n % p ==0: # p divide n evenly
        is_prime = False
        break
    
    if is_prime:
      prime_cache.append(n)
      yield n

In [ ]:
for p in prime_numbers():
  print(p)
  if p > 100:
    break

# Estudo e aplicações de exemplos demonstrados práticos do canal [Kite](https://www.youtube.com/watch?v=r7Dtus7N4pI)

## [Python Decorators in 15 Minutes](https://www.youtube.com/watch?v=r7Dtus7N4pI)


In [ ]:
def f1():
  print('Called f1')

In [ ]:
print(f1)

<function f1 at 0x7f12ff057b90>


In [ ]:
def f2(f):
  f()

In [ ]:
f2(f1)

Called f1


In [ ]:
def f1(func):
  def wrapper():
    print('Started')
    func()
    print('Ended')
  return wrapper



In [ ]:
def f():
  print('Hello')

In [ ]:
f1(f)()

Started
Hello
Ended


In [ ]:
print(f1(f))

<function f1.<locals>.wrapper at 0x7f12ff01e710>


In [ ]:
x = f1(f)

In [ ]:
x()

Started
Hello
Ended


In [ ]:
@f1
def f():
  print('sou uma função')

In [ ]:
f()

Started
sou uma função
Ended


# Estudo e aplicações de exemplos demonstrados práticos do canal [Carlos Melo](https://www.youtube.com/channel/UCxaCu5ht7d3jvisTpiW6vxw)

## [Resolvendo um Sistema de Equações Lineares com Python](https://www.youtube.com/watch?v=ZPmtWwZ5GuU)

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 1], [-3, 1]])
B = np.array([[6],[2]])

A_inversa = np.linalg.inv(A)

X = np.dot(A_inversa, B)

X

array([[1.],
       [5.]])

In [ ]:
np.linalg.solve(A,B)

array([[1.],
       [5.]])

In [ ]:
Z = np.array([[-1, -4, 0], [0, -4, 1], [-1, 0, -1]])
W = np.array([[20], [7], [13]])

print(Z)
print(W)

[[-1 -4  0]
 [ 0 -4  1]
 [-1  0 -1]]
[[20]
 [ 7]
 [13]]


In [ ]:
np.linalg.solve(Z, W)

LinAlgError: ignored